### ISSUE TITLE
IMU

### ISSUE THREAD

**Issue by isonoe18** [isonoe18/dragonfly#1]
# Inertial Measurement Unit

A program which takes the live data from an accelerometer and gyroscope to produce accurate roll, pitch and yaw angles of the drone.

## Task List

- [x] Sensor data recording
- [x] Convert sensor data to angle data
- [x] Use angle data to calculate true pitch, roll and yaw
